#ifndef MGFX_DEFINES_H_
#define MGFX_DEFINES_H_

#include <mx/mx.h>

#define MGFX_SUCCESS ((uint16_t)0)

typedef enum MGFX_SHADER_STAGE {
  MGFX_SHADER_STAGE_VERTEX = 0,
  MGFX_SHADER_STAGE_FRAGMENT,
  MGFX_SHADER_STAGE_COMPUTE,

  MGFX_SHADER_STAGE_COUNT
} MGFX_SHADER_STAGE;
 
#endif
